language: ruby
sudo: false
addons:
  apt:
    packages:
    - zlib1g-dev
    - libncurses5-dev
    - libtinfo-dev 
    - exonerate  
before_install:
  - gem update --system
  - export RUBYOPT="-W1"
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.5
  - 2.4.2
  - 2.5.0


